# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUTHORS',
            fields=[
                ('Author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Fname', models.CharField(max_length=200)),
                ('Mname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Suffix', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('Isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_AUTHORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AUTHORS')),
                ('Isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_COPIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_copies', models.IntegerField()),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_LOANS',
            fields=[
                ('Loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_out', models.DateField()),
                ('Date_in', models.DateField()),
                ('Date_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BORROWER',
            fields=[
                ('Card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Ssn', models.IntegerField()),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FINES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amt', models.CharField(max_length=200)),
                ('paid', models.IntegerField()),
                ('Loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BOOK_LOANS')),
            ],
        ),
        migrations.CreateModel(
            name='LIBRARY_BRANCH',
            fields=[
                ('Branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Branch_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book_loans',
            name='Branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.LIBRARY_BRANCH'),
        ),
        migrations.AddField(
            model_name='book_loans',
            name='Card_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BORROWER'),
        ),
        migrations.AddField(
            model_name='book_loans',
            name='Isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BOOK'),
        ),
        migrations.AddField(
            model_name='book_copies',
            name='Branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.LIBRARY_BRANCH'),
        ),
    ]
