# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160315_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Isbn',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
