# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160315_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='Author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
