# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160315_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_loans',
            old_name='Branch_id',
            new_name='Branch',
        ),
    ]
