# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160316_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_authors',
            old_name='Author_id',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book_copies',
            old_name='Branch_id',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='fines',
            old_name='Loan_id',
            new_name='Loan',
        ),
    ]
