# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Lname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Phone_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Ssn',
            field=models.CharField(default='', max_length=60),
        ),
    ]
