# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160317_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyBorrowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine', models.IntegerField(default=0)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BOOK')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.LIBRARY_BRANCH')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
    ]
