# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_currentlyborrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyborrowed',
            name='Date_out',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
