# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_currentlyborrowed_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loans',
            name='Loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
